### ISSUE TITLE
Bug in `market.js`

### ISSUE THREAD

**Issue by meetamit** [Koyfin/test-task#2]
Howdy. I came across a bug in here.

The Market class's `startNewDay()` method [incorrectly looks up last price](https://github.com/Koyfin/test-task/blob/53353a59f297aaf295851ee00b4acfe4d54c8b75/server/market.js#L15) by treating the method as an object: `this.getLastPrice[ticker]` 

As a result, when a new day starts, it is initialized with `[undefined]` and on every tick a `NaN` is appended.

That line should instead be:

    this.history[ticker] = [this.getLastPrice(ticker)]

---

There's also a (minor) typo in that file: assuming the ticker symbol **APPL** is meant to represent Apple Inc, then the symbol should actually be **AAPL**

**Comment by galkin** [comment]
Closed in #3

**Comment by galkin** [comment]
@meetamit, big thanks for your feedback!
